# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['server_entry.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('alpha_server/*.py', 'alpha_server'),
        ('alpha_server/brokers/*.py', 'alpha_server/brokers'),
        ('alpha_server/strategies/*.py', 'alpha_server/strategies'),
        ('alpha_server/models', 'alpha_server/models'),
    ],
    hiddenimports=[
        # web framework
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pydantic',
        'pydantic.deprecated.decorator',
        'multipart',
        # data / ML
        'yfinance',
        'pandas',
        'numpy',
        'sklearn',
        'sklearn.ensemble',
        'psycopg2',
        'beautifulsoup4',
        'bs4',
        'lxml',
        'apscheduler',
        'apscheduler.schedulers.background',
        'apscheduler.triggers.cron',
        'joblib',
        # v3.0+ security
        'jwt',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        # v3.1 LLM
        'anthropic',
        # alpha_server submodules (PyInstaller가 동적 import 시 누락 방지)
        'alpha_server',
        'alpha_server.audit_log',
        'alpha_server.auth',
        'alpha_server.credentials',
        'alpha_server.errors',
        'alpha_server.rate_limit',
        'alpha_server.risk_manager',
        'alpha_server.brokers',
        'alpha_server.brokers.base',
        'alpha_server.brokers.mock_broker',
        'alpha_server.brokers.alpaca_broker',
        'alpha_server.brokers.upbit_broker',
        'alpha_server.brokers.binance_broker',
        'alpha_server.brokers.kis_broker',
        'alpha_server.strategies',
        'alpha_server.strategies.spec',
        'alpha_server.strategies.indicators',
        'alpha_server.strategies.evaluator',
        'alpha_server.strategies.store',
        'alpha_server.strategies.executor',
        'alpha_server.strategies.nl_parser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 무거운 옵션 ML 라이브러리는 바이너리에서 제외 — 코드는 lazy import로 안전 폴백
        'xgboost',
        'lightgbm',
        'tensorflow',
        'tensorflow.keras',
        'keras',
        'torch',
        'transformers',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AlphaServer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AlphaServer',
)
